In [0]:
#import the libraries
import pandas as pd
import numpy as np

In [7]:
# Python3 program to find element 
# closet to given target. 
  
# Returns element closest to target in arr[] 
def findClosest(arr, n, target): 
  
    # Corner cases 
    if (target <= arr[0]): 
        return arr[0] 
    if (target >= arr[n - 1]): 
        return arr[n - 1] 
  
    # Doing binary search 
    i = 0; j = n; mid = 0
    while (i < j):  
        mid = (i + j) / 2
  
        if (arr[mid] == target): 
            return arr[mid] 
  
        # If target is less than array  
        # element, then search in left 
        if (target < arr[mid]) : 
  
            # If target is greater than previous 
            # to mid, return closest of two 
            if (mid > 0 and target > arr[mid - 1]): 
                return getClosest(arr[mid - 1], arr[mid], target) 
  
            # Repeat for left half  
            j = mid 
          
        # If target is greater than mid 
        else : 
            if (mid < n - 1 and target < arr[mid + 1]): 
                return getClosest(arr[mid], arr[mid + 1], target) 
                  
            # update i 
            i = mid + 1
          
    # Only single element left after search 
    return arr[mid] 
  
  
# Method to compare which one is the more close. 
# We find the closest by taking the difference 
# between the target and both values. It assumes 
# that val2 is greater than val1 and target lies 
# between these two. 
def getClosest(val1, val2, target): 
  
    if (target - val1 >= val2 - target): 
        return val2 
    else: 
        return val1 
  
# Driver code 
arr = [1, 2, 4, 5, 6, 6, 8, 9]  
n = len(arr) 
target = 11
print(findClosest(arr, n, target))

9

In [0]:
# intialise data of lists. 
data = {'Percentage':list(range(-200,200,4)), 'Score':list(range(0,100,1))} 
  
# Create DataFrame 
df = pd.DataFrame(data)

In [22]:
df

    Percentage  Score
0         -200      0
1         -196      1
2         -192      2
3         -188      3
4         -184      4
5         -180      5
6         -176      6
7         -172      7
8         -168      8
9         -164      9
10        -160     10
11        -156     11
12        -152     12
13        -148     13
14        -144     14
15        -140     15
16        -136     16
17        -132     17
18        -128     18
19        -124     19
20        -120     20
21        -116     21
22        -112     22
23        -108     23
24        -104     24
25        -100     25
26         -96     26
27         -92     27
28         -88     28
29         -84     29
..         ...    ...
70          80     70
71          84     71
72          88     72
73          92     73
74          96     74
75         100     75
76         104     76
77         108     77
78         112     78
79         116     79
80         120     80
81         124     81
82         128     82
83         132     83
84         136     84
85         140     85
86         144     86
87         148     87
88         152     88
89         156     89
90         160     90
91         164     91
92         168     92
93         172     93
94         176     94
95         180     95
96         184     96
97         188     97
98         192     98
99         196     99

[100 rows x 2 columns]

In [20]:
#closest percentage value in the database
closest = findClosest(df.Percentage, len(df.Percentage), -300)
print(closest)

-200

In [21]:
#scoring the user
score =df.index[df.Percentage == closest][0]
print(score)

0